//
// Created by geo71 on 1/03/2026.
//

#ifndef PROGRAMAICON_III_HOJA_DE_TRABAJO_2_ESTRUCTURAYNODOS_H
#define PROGRAMAICON_III_HOJA_DE_TRABAJO_2_ESTRUCTURAYNODOS_H


class estructuraynodos {
};


#endif //PROGRAMAICON_III_HOJA_DE_TRABAJO_2_ESTRUCTURAYNODOS_H